Домашние задание 4 - Работа с функциями для конвертации валют
UberSerg/PurpleSchool_JS_Novice pull request #6
Opened 2023-10-29 19:21 UTC by UberSerg

Привет, немного изменил нейминг в качестве более стандартных обозначений валют, в задании было $ я использовал USD, тоже самое с рублями. Также сделал для примера конвертацию в крону. Много других валют не стал делать, т.к. там однотипно.
Интуитивно хотелось бы курсы валют хранить в массиве, но мы его пока не проходили, поэтому сделал так, через IF.

2023-11-10 20:08 UTC, Levitinn requested changes

2023-11-10 20:08 UTC, Levitinn commented on 7-converter/app.js
> +function ConvertCurency (amountOfFunds, currencyOfFunds, targetCurrency) {
нейминг функции с должен быть с маленькой буквы

2023-11-10 20:08 UTC, Levitinn commented on 7-converter/app.js
> +    return conversionRates != null? amountOfFunds * conversionRates : null;
return amountOfFunds * conversionRates || null

2023-11-10 20:08 UTC, Levitinn commented on 7-converter/app.js
> +    conversionRates = giveConverionRate(currencyOfFunds,targetCurrency)
const conversionRates  .....

2023-11-10 20:08 UTC, Levitinn commented on 8-crypto/app.js
> +const check = (cryptedpassword, uncryptedpassword) => true ? crypto(cryptedpassword,1)===uncryptedpassword : false;
=> true ? crypto(cryptedpassword,1)===uncryptedpassword : false;
почему так ? у тебя же всегда будет выполняться блок crypto(cryptedpassword,1)===uncryptedpassword

2023-11-10 20:16 UTC, UberSerg commented on 8-crypto/app.js
> +const check = (cryptedpassword, uncryptedpassword) => true ? crypto(cryptedpassword,1)===uncryptedpassword : false;
Перепутал синтаксис тернарного оператора) Переделаю всё завтра. Спасибо за оперативное ревью

2023-11-12 11:14 UTC, Levitinn requested changes

2023-11-12 11:14 UTC, Levitinn commented on 8-crypto/app.js
> +const check = (cryptedpassword, uncryptedpassword) => crypto(cryptedpassword,1)===uncryptedpassword ? true : false;
`.....crypto(cryptedpassword,1) === uncryptedpassword ?......` не забываем про пробелы

2023-11-12 11:14 UTC, Levitinn commented on 7-converter/app.js
> +    conversionRates = giveConverionRate(currencyOfFunds,targetCurrency)
здесь я хотел сказать о том, что ты не указываешь тип переменной во время ее объявления. 
обязательно нужно указывать тип let/const при  инициализации переменной

2023-11-12 11:14 UTC, Levitinn commented on 10-array-clean/app.js
> +    return number>100 ? true : false;
number>100 забыл пробелы number > 100

2023-11-12 11:14 UTC, Levitinn commented on 10-array-clean/app.js
> +const deleteFunction = (number) => {
имя функции deleteFunction  говорит мне о том, что внутри этой функции находится логика по удалению функций.  Эта функция должна проверять, нужно ли удалять приходящий в нее элемент и возвращать ответ. Думаю, сюда подошло бы имя типа checkRemove (подумай, напиши свой вариант)

2023-11-12 11:14 UTC, Levitinn commented on 10-array-clean/app.js
> +const filterArr = (arr, deleteFunction) => {
логику всей этой функции можно сильно упростить, используя такие методы массива как filter или map. давай попробуем переделать решение на них, это многократно сократит кол-во кода и облегчит логику

2023-11-18 19:51 UTC, Levitinn approved these changes

2023-11-18 20:01 UTC, merged